[package]
name = "sized-chunks"
version = "0.5.0"
authors = ["Bodil Stokke <bodil@bodil.org>"]
edition = "2018"
license = "MPL-2.0+"
description = "Efficient sized chunk datatypes"
repository = "https://github.com/bodil/sized-chunks"
documentation = "http://docs.rs/sized-chunks"
readme = "./README.md"
categories = ["data-structures"]
keywords = ["sparse-array"]
exclude = ["release.toml", "proptest-regressions/**"]

[dependencies]
typenum = "1.10.0"
bitmaps = "2.0.0"
refpool = { version = "0.1.0", optional = true }

[dev-dependencies]
proptest = "0.9.1"
proptest-derive = "0.1.0"
